spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/shortlink?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password:

mybatis:
  configuration:
    map-underscore-to-camel-case: true
